# Site settings
description: Randomly talking about code and compilers
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://tadeuzagallo.com/blog" # the base hostname & protocol for your site

# User settings
username: Tadeu Zagallo
user_description: Software Engineer at Facebook
user_title: software engineer passionate about compilers
email: tadeuzagallo@gmail.com
twitter_username: tadeuzagallo
github_username: tadeuzagallo
gplus_username: tadeuzagallo
disqus_username: tadeuzagallo

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /blog/
  - title: Web Terminal
    url: /
  - title: Tags
    url: /blog/tags/
  - title: About Me
    url: /blog/about/

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
